export const cardImgAlt = {
    buenosAires: 'Capsul Nespresso Tokyo Lungo - капсули для кавоварки Nespresso',
    shanghaiLungo: 'shanghai lungo',
    viennaLungo: "vienna lungo",
    tokyoVivaltoLungo: 'tokyo lungo',
    stockholmLungo: 'stockholm lungo',
    capetownEnvivoLungo: 'cape town lungo',
    parisEspresso: 'paris espresso',
    istanbulEspresso: 'istanbul espresso',
    rioDeJaneiroEspresso: "rio de janeiro espresso",
    nocciola: 'nocciola',
    caramello: 'caramello',
    chiaro: 'chiaro',
    cioccolatino: 'cioccolatino',
    corto: 'corto',
    vaniglia: 'vaniglia',
    scuro: 'scuro',
    colombia: 'сolombia',
    capriccio: 'capriccio',
    cosi: 'сosi',
    ethiopia: 'ethiopia',
    indonesia: 'indonesia',
    peruOrganic: 'peru organic',
    nicaragua: 'nicaragua',
    frostedCaramelNuts: 'frosted caramel nut',
    seasonalDelightSpices: 'seasonal delight spices',
}

export const cardImgTitle = {
    buenosAires: 'Capsul Nespresso Tokyo Lungo - Капсули для кавоварки Nespresso',
    shanghaiLungo: 'shanghai lungo',
    viennaLungo: "vienna lungo",
    tokyoVivaltoLungo: 'tokyo lungo',
    stockholmLungo: 'stockholm lungo',
    capetownEnvivoLungo: 'cape town lungo',
    parisEspresso: 'paris espresso',
    istanbulEspresso: 'istanbul espresso',
    rioDeJaneiroEspresso: "rio de janeiro espresso",
    nocciola: 'nocciola',
    caramello: 'caramello',
    chiaro: 'chiaro',
    cioccolatino: 'cioccolatino',
    corto: 'corto',
    vaniglia: 'vaniglia',
    scuro: 'scuro',
    colombia: 'сolombia',
    capriccio: 'capriccio',
    cosi: 'сosi',
    ethiopia: 'ethiopia',
    indonesia: 'indonesia',
    peruOrganic: 'peru organic',
    nicaragua: 'nicaragua',
    frostedCaramelNuts: 'frosted caramel nut',
    seasonalDelightSpices: 'seasonal delight spices',
}