export const nameUkraine = {
    buenosAires: 'буенос-айрес лунго',
    shanghaiLungo: 'шанхай лунго',
    viennaLungo: "віденський лунго",
    tokyoVivaltoLungo: 'токійський лунго',
    stockholmLungo: 'стокгольм лунго',
    capetownEnvivoLungo: 'кейптаун лунго',
    parisEspresso: 'зерно та печиво',
    istanbulEspresso: 'обсмажений та фруктовий',
    rioDeJaneiroEspresso: "трав'яний та пряний",
    nocciola: 'горіх',
    caramello: 'карамель',
    chiaro: 'світлий',
    cioccolatino: 'шоколадинка',
    corto: 'короткий',
    vaniglia: 'ваніль',
    scuro: 'насичений',
    colombia: 'колумбія',
    capriccio: 'каприз',
    cosi: 'ніжний',
    ethiopia: 'ефіопія',
    indonesia: 'індонезія',
    peruOrganic: 'перу',
    nicaragua: 'нікарагуа',
    frostedCaramelNuts: 'обсмажений карамельний',
    seasonalDelightSpices: 'cезонне радість зі спеціями',

};

export const nameOrigin = {
    buenosAires: 'buenos aires lungo',
    shanghaiLungo: 'shanghai lungo',
    viennaLungo: "vienna lungo",
    tokyoVivaltoLungo: 'tokyo lungo',
    stockholmLungo: 'stockholm lungo',
    capetownEnvivoLungo: 'cape town lungo',
    parisEspresso: 'paris espresso',
    istanbulEspresso: 'istanbul espresso',
    rioDeJaneiroEspresso: "rio de janeiro espresso",
    nocciola: 'nocciola',
    caramello: 'caramello',
    chiaro: 'chiaro',
    cioccolatino: 'cioccolatino',
    corto: 'corto',
    vaniglia: 'vaniglia',
    scuro: 'scuro',
    colombia: 'сolombia',
    capriccio: 'capriccio',
    cosi: 'сosi',
    ethiopia: 'ethiopia',
    indonesia: 'indonesia',
    peruOrganic: 'peru organic',
    nicaragua: 'nicaragua',
    frostedCaramelNuts: 'frosted caramel nut',
    seasonalDelightSpices: 'seasonal delight spices',
}