export const shortDescription = {
    buenosAires: 'солодощі та злаки',
    shanghaiLungo: 'фруктовий з ніжною кислинкою',
    viennaLungo: "м'який та округлий",
    tokyoVivaltoLungo: 'квітковий і cкладний aромат',
    stockholmLungo: 'багатий і насичений',
    capetownEnvivoLungo: 'міцний та обсмажений',
    parisEspresso: 'паризький еспресо',
    istanbulEspresso: 'стамбульський еспресо',
    rioDeJaneiroEspresso: 'ріо-де-жанейрський еспресо',
    capriccio: 'багатий і характерний',
    caramello: 'ніжний та карамельний',
    chiaro: 'для солодких та ніжних рецептів з молоком',
    cioccolatino: 'ніжний та шоколадний',
    colombia: 'фруктовий та жвавий',
    corto: 'пряний та обсмажений',
    cosi: 'ніжний і дбайливо обсмажений',
    ethiopia: 'квітковий та яскравий',
    indonesia: 'багатий та деревний',
    frostedCaramelNuts: 'блонд карамель і мигдаль',
    nicaragua: 'солодкий та гармонійний',
    nocciola: 'багатий і горішковий.',
    peruOrganic: 'фруктовий та елегантний',
    scuro: 'обсмажений та збалансований',
    seasonalDelightSpices: 'спеції та вино',
    vaniglia: 'з кремовим смаком та ванільним ароматом',
};